Feature: ver auto-avaliacao
	As a: professor
	I want to: ver como os meus alunos se auto avaliam
Scenario: Sem alunos com discrepancia
	Given: Eu estou logado como professor, com login “xyz” e senha “1234”
	And: Eu posso ver a auto-avaliacao do aluno “Jose” com “MPA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Jose” foi avaliado com “MANA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: Eu posso ver a auto-avaliacao do aluno “Efraim” com “MPA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MPA” em “Entender motivacao e conceitos de testes” e “MPA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Efraim” foi avaliado com “MA” em “Entender motivacao e conceitos de requisitos”, “MA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: Eu posso ver a auto-avaliacao do aluno “Eliezer” com “MA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Eliezer” foi avaliado com “MA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	When: Eu entro na pagina “avaliacoes dos alunos”
	Then: Eu posso ver “0” no campo “numero de alunos com avaliacoes discrepantes”, “0%” no campo “percentual de alunos com avaliacoes discrepantes” e a mensagem “nao ha alunos com avaliacoes discrepantes” no campo “lista de alunos com avaliacoes discrepantes” 

Scenario: Alunos discrepantes
	Given: Eu estou logado como professor, com login “xyz” e senha “1234”
	And: Eu posso ver a auto-avaliacao do aluno “Jose” com “MPA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Jose” foi avaliado com “MANA” em “Entender motivacao e conceitos de requisitos”, “MANA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: Eu posso ver a auto-avaliacao do aluno “Efraim” com “MPA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MPA” em “Entender motivacao e conceitos de testes” e “MPA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Efraim” foi avaliado com “MA” em “Entender motivacao e conceitos de requisitos”, “MA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: Eu posso ver a auto-avaliacao do aluno “Eliezer” com “MA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	And: O aluno “Eliezer” foi avaliado com “MA” em “Entender motivacao e conceitos de requisitos”, “MPA” em “Entender motivacao e conceitos de gerencia de configuracao”, “MPA” em “Entender motivacao e conceitos de gerencia de projetos”, “MA” em “Entender motivacao e conceitos de testes” e “MA” em “Entender motivacao e conceitos de implementacao”
	When: Eu entro na pagina “avaliacoes dos alunos”
	Then: Eu posso ver “1” no campo “numero de alunos com avaliacoes discrepantes”, “33,33%” no campo “percentual de alunos com avaliacoes discrepantes” e o nome “Jose” no campo “lista de alunos com avaliacoes discrepantes”
